# Generated by Django 4.2.30 on 2026-06-17 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('org_id', models.CharField(max_length=200, verbose_name='Snyk Org ID')),
                ('jira_project_key', models.CharField(max_length=50, verbose_name='Jira Project Key')),
                ('project_id', models.CharField(blank=True, max_length=200, verbose_name='Snyk Project ID')),
                ('api_endpoint', models.CharField(blank=True, max_length=500, verbose_name='API Endpoint')),
                ('jira_project_id', models.CharField(blank=True, max_length=50, verbose_name='Jira Project ID')),
                ('jira_ticket_type', models.CharField(default='Bug', max_length=50, verbose_name='Jira Ticket Type')),
                ('assignee_id', models.CharField(blank=True, max_length=200, verbose_name='Assignee ID')),
                ('assignee_name', models.CharField(blank=True, max_length=200, verbose_name='Assignee Name')),
                ('labels', models.CharField(blank=True, max_length=500, verbose_name='Labels (comma-separated)')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20, verbose_name='Min Severity')),
                ('issue_type', models.CharField(choices=[('all', 'All'), ('vuln', 'Vulnerabilities only'), ('license', 'Licenses only')], default='all', max_length=20, verbose_name='Issue Type')),
                ('maturity_filter', models.CharField(blank=True, max_length=200, verbose_name='Maturity Filter')),
                ('priority_score_threshold', models.IntegerField(blank=True, null=True, verbose_name='Priority Score Threshold (0–1000)')),
                ('priority_is_severity', models.BooleanField(default=False, verbose_name='Priority = Severity')),
                ('if_upgrade_available_only', models.BooleanField(default=False, verbose_name='Upgradable issues only')),
                ('dry_run', models.BooleanField(default=False, verbose_name='Dry run')),
                ('debug', models.BooleanField(default=False, verbose_name='Debug logging')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cron_expression', models.CharField(help_text="Standard 5-part cron: minute hour day month weekday. E.g. '0 9 * * 1' = every Monday at 9am UTC", max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='tickets.configuration')),
            ],
        ),
        migrations.CreateModel(
            name='RunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_by', models.CharField(default='manual', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('output', models.TextField(blank=True)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('configuration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='tickets.configuration')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='tickets.schedule')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
